export const userConstants = {
  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  ADD_REQUEST: 'USERS_ADD_REQUEST',
  ADD_SUCCESS: 'USERS_ADD_SUCCESS',
  ADD_FAILURE: 'USERS_ADD_FAILURE',

  UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

  FILTER_SUCCESS: 'FILTER_SUCCESS',
};
